export const theme = {
  colors: {
    background: "#f7f9fb",
    surface: "#ffffff",
    surfaceSoft: "#f2f4f6",
    border: "#c7c4d8",
    borderStrong: "#e0e3e5",
    text: "#191c1e",
    textMuted: "#464555",
    textSubtle: "#777587",
    primary: "#3525cd",
    primarySoft: "#4f46e5",
    primaryTint: "#dad7ff",
    secondary: "#006c49",
    secondaryTint: "#6cf8bb",
    destructive: "#ba1a1a",
    destructiveTint: "#ffdad6",
    success: "#006c49",
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    pageMargin: 20,
    cardPadding: 16,
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 12,
    full: 9999,
  },
  fonts: {
    display: "System",
    headline: "System",
    body: "System",
    mono: "System",
  },
} as const;
